name: 🐛 Report a bug
description: Report a bug to help us improve the library.
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce the bug
      description: "Please share your code snippet or steps to reproduce the bug."
      placeholder: |
        1. [ex: Step 1]
        2. [ex: Step 2]
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    attributes:
      label: Version of the library
      placeholder: "2.x.x"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
